-- Active: 1697272745728@@127.0.0.1@3306@first
SELECT * FROM programmers;
SELECT NAME, FLOOR(DATEDIFF(CURDATE(), DOB) / 365) AS age FROM programmers;
SELECT NAME FROM programmers WHERE NAME LIKE '%H';

SELECT NAME,DOB FROM programmers WHERE MONTH(DOB)="01";

SELECT * FROM studies;

SELECT count(*) FROM studies WHERE COURSE="Pgdca";

SELECT NAME,CCOST FROM studies WHERE CCOST>=5000 AND CCOST<=10000;

SELECT COUNT(*) FROM programmers WHERE PROF1="Cobol" OR PROF2="Cobol" OR PROF1="Pascal" OR PROF2="Pascal";

select count (*) from programmers where PROF1 not in ('Pascal','C') and PROF2 not in ('Pascal','C');


CREATE Table Software(NAME VARCHAR(8),TITLE VARCHAR(20),DEV_IN VARCHAR(8),SCOST DECIMAL(7,2),DCOST INT(5),SOLD INT(3))

show TABLES;

SELECT * FROM software

SELECT AVG(`SCOST`) FROM software WHERE DEV_IN="PASCAL" 

SELECT NAME, FLOOR(DATEDIFF(CURDATE(), DOB) / 365) AS age FROM programmers;

SELECT `NAME` FROM studies WHERE `COURSE`="Dap"

SELECT * FROM software

SELECT * FROM software WHERE `SOLD`= (SELECT MAX(`SOLD`) from software)

SELECT NAME,DOB FROM programmers WHERE MONTH(DOB)=01;
SELECT * FROM studies WHERE `CCOST`= (SELECT MIN(CCOST) from studies);
SELECT * FROM studies WHERE COURSE="Pgdca"

SELECT SUM(`SOLD`) AS Total FROM software WHERE `DEV_IN`="C";

SELECT * FROM software WHERE `NAME`="RAMESH";

SELECT * FROM studies WHERE `SPACE`="SDBT";
SELECT * FROM software WHERE (`DCOST`*`SOLD`)>=20000;
SELECT  ROUND(`DCOST`/`SCOST`) AS COPIES FROM software;
SELECT MAX(`DCOST`) as HIGHEST_DEVELOPMENT_COST FROM software WHERE `DEV_IN`="BASIC";
SELECT * FROM software WHERE (`SOLD`*`SCOST`)>=`DCOST`;
SELECT * FROM software WHERE `DEV_IN`="dbase";
SELECT * FROM studies WHERE `SPACE`="BITS";
SELECT * FROM studies WHERE `CCOST`>=5000 AND `CCOST`<=10000;
SELECT AVG(`CCOST`) AS AVERGAE_COURSE_COST FROM studies;
SELECT * FROM programmers WHERE `PROF1`='C' or `PROF2`='C';
SELECT * FROM programmers WHERE PROF1 in ("COBOL","PASCAL") or `PROF2` in ("COBOL","PASCAL");
SELECT * FROM programmers WHERE NOT(PROF1 in ("C","PASCAL") or `PROF2` in ("C","PASCAL"));
SELECT MAX(ROUND(DATEDIFF(CURDATE(), DOB) / 365)) AS age from programmers WHERE SEX="M";
SELECT ROUND(AVG(ROUND(DATEDIFF(CURDATE(), DOB) / 365))) AS AVERAGE_AGE from programmers WHERE SEX="F";
SELECT * FROM programmers ORDER BY DATEDIFF(CURDATE(),DOJ) DESC;